In [25]:
import tensorflow as tf
import numpy as np

### Load the MNIST dataset 

In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

 The Data consist on an array of  60,000 images of  28 by 28 pixels

In [33]:
print(tf.size(x_train))
print(tf.shape(x_train))
print("Size of test data is:",len(x_test))
print("Size of training data is:",len(x_train))

tf.Tensor(47040000, shape=(), dtype=int32)
tf.Tensor([60000    28    28], shape=(3,), dtype=int32)
Size of test data is: 10000
Size of training data is: 60000


Building the model

In [34]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
#Sets the activation function as a Rectified Linear Unit RLU 
  tf.keras.layers.Dense(128, activation='relu'),
#Sets the Droput Parameter 
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [44]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-11.815196 , -14.45476  ,  -8.402252 ,   6.828214 , -29.589947 ,
         12.564654 , -16.543972 , -11.983845 ,  -8.777598 ,  -4.3232255]],
      dtype=float32)

In [36]:
tf.nn.softmax(predictions).numpy()

array([[0.11215116, 0.05963413, 0.06688239, 0.06523422, 0.11470231,
        0.12410232, 0.09550026, 0.20340957, 0.08946665, 0.06891703]],
      dtype=float32)

In [37]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [39]:
loss_fn(y_train[:1], predictions).numpy()

2.086649

In [40]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [41]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 58us/sample - loss: 0.2988 - accuracy: 0.9136
Epoch 2/5
60000/60000 [==============================] - 3s 45us/sample - loss: 0.1451 - accuracy: 0.9573
Epoch 3/5
60000/60000 [==============================] - 3s 49us/sample - loss: 0.1091 - accuracy: 0.9678
Epoch 4/5
60000/60000 [==============================] - 3s 45us/sample - loss: 0.0883 - accuracy: 0.9735
Epoch 5/5
60000/60000 [==============================] - 3s 48us/sample - loss: 0.0773 - accuracy: 0.9750


In [42]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 0s - loss: 0.0755 - accuracy: 0.9770


[0.07552082368494012, 0.977]